FROM ubuntu:16.04



# install hyperbrowser dependencies
RUN apt-get update && apt-get install -y \
   python2.7 \
   perl \
   r-base \
   libcairo2-dev \
   libzmq-dev \
   xvfb \
   libmagickcore-dev \
   rsync \
   python2.7-dev \
   libpq-dev \
   libglu1-mesa-dev

